### ISSUE TITLE
Login Page Authentication

### ISSUE THREAD

**Issue by JohnnyUrosevic** [rise-summer/team6-education#1]
### Tasks:
- Should use JWT to store authentication credentials.
- On successful login we should redirect to the dashboard page. 
- Login credentials need to be stored securely in the MongoDB database.
- Credentials should specify if the user is a student, a teacher, or an admin

**Comment by baosimple** [comment]
I can handle this one

**Comment by JohnnyUrosevic** [comment]
Closed by #11
